name: Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release Tag (1.x.x)'
        required: true

jobs:
  build:
    name: Build Executable
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-13, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          onefile: true
          output-file: Easy-MHYY-v${{ inputs.release-tag }}
          company-name: Mooneze
          product-name: Easy-MHYY
          file-version: ${{ inputs.release-tag }}
          product-version: ${{ inputs.release-tag }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
            
  upload:
    name: Upload To Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dists/
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          name: Easy-MHYY v${{ inputs.release-tag }}
          tag_name: v${{ inputs.release-tag }}
          files: dists/*
